on:
  schedule:
    - cron: '0 0 * * *' # once a day
  push:
    branches:
      - main
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v3
      with:
        token: ${{ secrets.PROFILE_STATS_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name ${{ secrets.USER_NAME }}
        git config user.email ${{ secrets.USER_EMAIL }}
        git add .
        git commit -m "📈 update profile stats"
        git push
        fi
